export const cardDatas = [
  {
    title: "Lighthouse Design System",
    description: `Open-sourced Design System solution to re-invent designing and developing workflows.`,
    duration: "2020 ~ ",
    slug: "lighthouse-design-system",
    tags: ["design", "develop"],
  },
  {
    title: "Harbor School",
    description: `As the founder of Harbor School, I learned how software impacts people and society and markets.`,
    duration: "2018 ~ 2020",
    slug: "harbor-school",
    tags: ["develop", "marketing"],
  },
  {
    title: "Framer Korea",
    description: `Lead Developer (React) / Program Manager`,
    duration: "2018 ~ ",
    slug: "framer-korea",
    tags: ["develop", "design"],
  },
  {
    title: "Seoul Lifelong Education Institute (SLEI) Magazine",
    description: `Developed whole website (React + Python + Github CI)`,
    duration: "Oct 2020 ~ Dec 2020",
    slug: "seli",
    tags: ["develop"],
  },
  {
    title: "Pulsen - Motion based Chatbot",
    description: `Developed whole website (React + Framer)`,
    duration: "Mar 2019 - May 2019",
    slug: "pulsen",
    tags: ["develop"],
  },
  {
    title: "Cnyttan - Online Shopping Site",
    description: `Developed whole website (Wordpress + React)`,
    duration: "Oct 2018 - Nov 2018",
    slug: "cnyttan",
    tags: ["develop"],
  },
  // {
  //   title: "freelance works",
  //   description: `Make web applications to solve real-world challenges designing new development structures.`,
  //   duration: "2014 ~ ",
  //   slug: "freelance-works",
  // },
  {
    title: "vincent project",
    description: ``,
    duration: "2014 ~ 2016",
    outlink: "https://www.instagram.com/vincent.project/",
    tags: ["design", "develop"],
  },
]
